# Generated by Django 4.1.5 on 2023-01-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_big_featured_course_small_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='big_featured',
            new_name='featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='small_featured',
        ),
    ]
