# Generated by Django 4.1.5 on 2023-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
