# Generated by Django 4.1.5 on 2023-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_author_name_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(default='1h 30m', max_length=100),
        ),
    ]
