# Generated by Django 4.1.5 on 2023-01-17 18:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attachments',
            field=tinymce.models.HTMLField(default='Test'),
        ),
    ]
