# Generated by Django 4.1.5 on 2023-01-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_item_attachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
