# Generated by Django 4.1.5 on 2023-01-18 05:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=300)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('attachments', tinymce.models.HTMLField(default='Test')),
                ('isVideo', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.file')),
            ],
        ),
    ]
