# Generated by Django 4.1.5 on 2023-01-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
