# Generated by Django 4.1.5 on 2023-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
