# Generated by Django 4.1.5 on 2023-01-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_contactmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
