# Generated by Django 4.1.5 on 2023-03-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_delete_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
