# Generated by Django 4.1.5 on 2023-03-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
