# Generated by Django 4.1.5 on 2023-01-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_user_question_author_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
    ]
